In [5]:
!pip install numpy


In [6]:
import numpy as np

In [90]:
A = np.array([[1, 1, 1, 1],
              [2, -1, 3, 4],
              [-3, 2, -2, 5],
              [1, -1, 4, -1]])

B = np.array([10, 8, -3, 5])

ans = np.linalg.solve(A, B)

variables = ['x', 'y', 'z', 'w']

print("1. Solve the system using elimination method in matrix form:")
for var, value in zip(variables, ans):
    print(f"{var} = {value:.2f}")

1. Solve the system using elimination method in matrix form:
x = 3.44
y = 4.70
z = 1.62
w = 0.24


In [84]:
A = np.array([[2100, 1500], 
              [-600, 900]])

B = np.array([12, 15])

I2, I3 = np.linalg.solve(A, B)
I1 = I2 + I3

print("2.Solving for the currents of a electrical network can be determined by solving it as a system of linear equations. :")
print(f"I1 = {I1:.4f} A")
print(f"I2 = {I2:.4f} A")
print(f"I3 = {I3:.4f} A")


2.Solving for the currents of a electrical network can be determined by solving it as a system of linear equations. :
I1 = 0.0097 A
I2 = -0.0042 A
I3 = 0.0139 A


In [82]:
import numpy as np


A = np.array([[2, 1, 3],
              [1, 2, 1],
              [3, 1, 2]])
print("3.Find the inverse of matrix A. :")
print(np.linalg.inv(A))

3.Find the inverse of matrix A. :
[[-0.375 -0.125  0.625]
 [-0.125  0.625 -0.125]
 [ 0.625 -0.125 -0.375]]
